// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 insertVector() ", "[example]")
{
	const int SIZE = 10;
	int usernum, idx;
	vector<int> number(10);

	srand(time(0));
	makeVector(number);
	printVector(number);
	usernum = 15;
	for (int i = 0; i < number.size(); i++)
	{
		if (number[i] > usernum)
		{
			idx = i;
			break;
		}
	}
	insertVector(number, usernum);
	printVector(number);

	REQUIRE(number[idx] == usernum);
}
// tests for exercise 2
TEST_CASE("Ex2 deleteVector()", "[example]")
{
	const int SIZE = 30;
	int usernum, idx, result, size;
	int cnt = 0;
	int tcnt = 0;
	vector<int> number(SIZE);
	vector<int>::iterator iter;

	srand(time(0));

	makeVector(number);
	printVector(number);
	iter = number.begin();
	while (1)
	{
		iter = find(iter, number.end(), usernum);
		if (iter == number.end())
		{
			break;
		}
		cnt += 1;
		iter += 1;
		if (cnt >= 2)
			usernum = *iter;
	}
	size = number.size();
	iter = number.begin();
	while ((iter = find(iter, number.end(), usernum)) != number.end())
	{
		number.erase(iter);
		cnt += 1;
	}
	REQUIRE(number.size() == size - cnt);
}